nome=input("Digite o nome do individuo: ")
cidade=input("Digite a cidade do individuo: ")
estado=input("Digite o estado do individuo: ")
data_nasc=input("Digite a data de nascimento do individuo: ")
print("--------------------------------------")
print(f"Nome do invididuo {nome}")
print(f"Cidade do invididuo {cidade}")
print(f"Estado do invididuo {estado}")
print(f"Data de nascimento do invididuo {data_nasc}")